import asyncio
import aiomysql
import oracledb

async def seed_mysql():
    conn = await aiomysql.connect(
        host="mysql-test",
        port=3306,
        user="root",
        password="mysql_pass",
        db="test_db"
    )
    async with conn.cursor() as cur:
        await cur.execute("CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), email VARCHAR(255))")
        await cur.execute("TRUNCATE TABLE users")
        await cur.execute("INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com'), ('Jane Smith', 'jane@example.com')")
        await conn.commit()
    conn.close()

def seed_oracle():
    dsn = "oracle-test:1521/FREEPDB1"
    with oracledb.connect(user="system", password="oracle_pass", dsn=dsn) as conn:
        with conn.cursor() as cur:
            try:
                cur.execute("CREATE TABLE users (id NUMBER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR2(255), email VARCHAR2(255), PRIMARY KEY(id))")
            except oracledb.DatabaseError as e:
                error, = e.args
                if error.code == 955: # name is already used by an existing object
                    pass
                else:
                    raise
            
            cur.execute("TRUNCATE TABLE users")
            cur.execute("INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com')")
            cur.execute("INSERT INTO users (name, email) VALUES ('Jane Smith', 'jane@example.com')")
            conn.commit()

async def main():
    try:
        await seed_mysql()
        print("MySQL seeded successfully.")
    except Exception as e:
        print(f"MySQL error: {e}")
        
    try:
        seed_oracle()
        print("Oracle seeded successfully.")
    except Exception as e:
        print(f"Oracle error: {e}")

if __name__ == "__main__":
    asyncio.run(main())
